version: '3.8'
services:
        webserver:
                build:
                        context: .
                        dockerfile: ./webserver/Dockerfile
                image: webserver_${NAME}_image
                container_name: webserver_${NAME}_container
                stdin_open: true
                #tty: true
                #command: /bin/bash
                command: flask run
                environment:
                        - NGX_PORT=${NGX_PORT}
                        - NGX_HOST=localhost
                        - FLASK_ENV=development
                        - FLASK_APP=/root/webserver/server.py
                        - FLASK_RUN_HOST=0.0.0.0
                        - FLASK_RUN_PORT=${WEB_PORT}
                volumes:
                        - ${STORAGE}:/mnt/data
                restart: always
        tiler:
                build:
                        context: .
                        dockerfile: ./tiler/Dockerfile
                image: tiler_${NAME}_image
                container_name: tiler_${NAME}_container
                stdin_open: true
                #tty: true
                #command: /bin/bash
                command: flask run
                environment:
                        - FLASK_ENV=development
                        - FLASK_APP=/root/tiler/server.py
                        - FLASK_RUN_HOST=0.0.0.0
                        - FLASK_RUN_PORT=${TIL_PORT}
                volumes:
                        - ${STORAGE}:/mnt/data
                restart: always
                environment:
                        - PYTHONUNBUFFERED=1
        labeler:
                build:
                        context: .
                        dockerfile: ./labeler/Dockerfile
                image: labeler_${NAME}_image
                container_name: labeler_${NAME}_container
                stdin_open: true
                #tty: true
                #command: /bin/bash
                command: flask run
                environment:
                        - FLASK_ENV=development
                        - FLASK_APP=/root/labeler/server.py
                        - FLASK_RUN_HOST=0.0.0.0
                        - FLASK_RUN_PORT=${LAB_PORT}
                volumes:
                        - ${STORAGE}:/mnt/data
                restart: always
                environment:
                        - PYTHONUNBUFFERED=1
        infer:
                build:
                        context: .
                        dockerfile: ./infer/Dockerfile
                image: infer_wv                                                      
                container_name: blazing_dmitriy
                stdin_open: true
                command: python3 /root/infer/server.py
                volumes:
                        - ${STORAGE}:/mnt/data
                restart: always
                environment:
                        - PYTHONUNBUFFERED=1
        nginx:
                build:
                        context: ./nginx
                        dockerfile: ./Dockerfile
                image: nginx_${NAME}_image
                container_name: nginx_${NAME}_container
                restart: always
                ports:
                        - ${NGX_PORT}:80
                links:
                        - webserver
                        - tiler
                        - labeler
